   //------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeroHunger.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class collection_rqsts
    {
        public int id { get; set; }
        public int restaurant_id { get; set; }
        public System.DateTime expiry_date { get; set; }
        public string status { get; set; }
    
        public virtual Restaurant Restaurant { get; set; }
    }
}
