//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeroHunger.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Distribution
    {
        public int id { get; set; }
        public int request_id { get; set; }
        public int emp_id { get; set; }
        public System.DateTime dist_date { get; set; }
        public string status { get; set; }
    
        public virtual collection_rqsts collection_rqsts { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
