//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeroHunger.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ZH_DBEntities16 : DbContext
    {
        public ZH_DBEntities16()
            : base("name=ZH_DBEntities16")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<collection_rqsts> collection_rqsts { get; set; }
        public virtual DbSet<Distribution> Distributions { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Restaurant> Restaurants { get; set; }
    }
}
