//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductBuy.EntityF
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersOrder
    {
        public int uoId { get; set; }
        public int userId { get; set; }
        public int orderId { get; set; }
        public int subTotal { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual User User { get; set; }
    }
}
